### ISSUE TITLE
Respect "hidden" tag

### ISSUE THREAD

**Issue by guykisel** [stjohnjohnson/cucumber-junit#11]
The JSON generated by cucumber-js for my tests has Before and After steps that are tagged in the JSON as "hidden". It would be nice if cucumber-junit respected the the "hidden" tag and left these steps out of the generated xml.

Example excerpt:
```
"steps": [
          {
            "keyword": "Before ",
            "hidden": true,
            "result": {
              "duration": 6105808,
              "status": "passed"
            },
            "match": {}
          },
          {
            "name": "I log in as user \"username\" and password \"password\"",
            "line": 9,
            "keyword": "When ",
            "result": {
              "duration": 33224808,
              "status": "passed"
            },
            "match": {}
          },
```

**Comment by stjohnjohnson** [comment]
Interesting.  Good catch.  I would want it to show up if it failed there.

**Comment by stjohnjohnson** [comment]
+ cucumber-junit@1.4.0

**Comment by guykisel** [comment]
Nice, thanks!

**Comment by RomkeVdMeulen** [comment]
I'm running into a problem. Skipping hidden steps in the JUnit report is fine when they pass. But if an error occurs in a hidden step then the Cucumber run will exit with 1, failing the build, but the report doesn't show where the error occurred.

Perhaps hidden steps should only be skipped from the report if they've passed?
