### ISSUE TITLE
path to cucumber-junit in sample on wiki

### ISSUE THREAD

**Issue by MikeCaspar** [stjohnjohnson/cucumber-junit#12]
Hi there...
I'm trying to use this module to work with nodejs and jenkins.

The following command has an error for someone who doesn't have cucumber-junit loaded into --global.

```
node_modules/.bin/cucumber-js --format=json | cucumber-junit > output_JUnit.xml
```

needs to read
```
node_modules/.bin/cucumber-js --format=json | node_modules/./bin/cucumber-junit > output_JUnit.xml
```

or of course, it might work by installing into --global in the first place (not my particular preference).

**Comment by stjohnjohnson** [comment]
Ahh, you either need it in global, or you can launch it from your npm script.  If you do it via the npm script, the node_modules/.bin directory will automatically be added to your path.

**Comment by stjohnjohnson** [comment]
Resolved :)
