### ISSUE TITLE
Tests fail if any output from either console or util.log

### ISSUE THREAD

**Issue by MikeCaspar** [stjohnjohnson/cucumber-junit#13]
I had some trouble getting things to work until I realized that any output at all to console (using console.log) or require("util").log("text") both create exceptions.

I have noticed that -json starts normal output with an array.

I am working with an express app, and there is some logging.  I realize that probably I should go ahead and remove any logging of this nature some day, but for now, I'd rather ask for a feature or parameter of some sort to ignore this type of text.  Let me know if you're interested and I can send you some output from -json to test with. 

If there is something completely wrong that I'm doing and I need to run the initial command differently, please let me know and perhaps add as instructions for someone else on the wiki ?

Thanks.. for my first attempt, this did the trick.. Thanks for writing it.

**Comment by stjohnjohnson** [comment]
Sadly, the only output I get from cucumber is via STDOUT.  If you add any extra information, it is muddled in the JSON.  If I could hook into cucumber to write out to a file instead for json, that would be better.

**Comment by MikeCaspar** [comment]
Understood... I'll try the file route.
