### ISSUE TITLE
dependencies warning

### ISSUE THREAD

**Issue by MikeCaspar** [stjohnjohnson/cucumber-junit#14]
Is there a reason to be forced to an old version of node?

warning: 
cucumber-junit@1.3.0: wanted: {"node":"~0.10.20"} (current: {"node":"0.12.7","npm":"2.11.3"})

**Comment by stjohnjohnson** [comment]
No reason, that's just what I built it on at the time.

**Comment by stjohnjohnson** [comment]
Fixed in 
+ cucumber-junit@1.3.1
