### ISSUE TITLE
Improvement: support for custom properties

### ISSUE THREAD

**Issue by szikszail** [stjohnjohnson/cucumber-junit#15]
In case of automating the failure investigation and filter out or handle common errors (element not found, wait timeout or common application specific errors) we need to sign somewhere in the JSON, that what type of error happened, what the cause of the failure.

In the JUnit XML format it is not a problem, using `properties` in `testsuite` tags.

If I make a hook and process the failing steps in my TA framework, there is no way to include the common error type or any custom properties to cucumber JSON. If I make a custom formatter, what makes an extended cucumber JSON format, that could be a solution. It could add a `properties` attribute to scenario's object.

In this case we have to improve cucumber-junit to support these custom properties and pass through them as `tags` passed through now.

**Would this be a good improvement and useful to others, or not?**
What do you think @stjohnjohnson ?

If you think it is a good idea, I will implement it immediately.

**Comment by stjohnjohnson** [comment]
Ahh, this is interesting.  I'd love to see the custom formatter.  This could be quite useful.

**Comment by szikszail** [comment]
I would really like to publish it to github, but I cannot, because it is a project work :)

**Comment by stjohnjohnson** [comment]
Hmm, so it's going to be a custom key added to the JSON output that you want to turn into properties?  Or it's going to be generic enough so that others can use it?

**Comment by szikszail** [comment]
I planned to add a simple `properties` key to `scenario` and the content of it will be added to `testsuite`'s `properties`. Like `tags`. So I guess it would be generic.

**Comment by stjohnjohnson** [comment]
Sorry for the delay, yes that would work great.

**Comment by stjohnjohnson** [comment]
Thanks for the PR!  Code was shipped in cucumber-junit@1.5.0

**Comment by szikszail** [comment]
Thank you!
