### ISSUE TITLE
how do i get json file in the output directory

### ISSUE THREAD

**Issue by ahmedusa** [stjohnjohnson/cucumber-junit#19]
I am trying to create a standard json file into the output directory but i can see only xml file in their. please help on this issue.

**Comment by stjohnjohnson** [comment]
I'm not sure what you mean by json file?  This creates junitXML files.

**Comment by ahmedusa** [comment]
So, I am using cucumberjs-junitxml and it is creating a cucumber-test-result.xml in the tests/features/output directory on the run. is there any way i can create a cucumber-test-result.json file instead of .xml file. I am looking for jason file so that jenkins can read it for cucumber report.

For more information: if you navigate to cucumberjs-junitxml/tests/mocks/input.json file, this is the format i am looking for in the tests/features/output directory.

Appreciate your response.

**Comment by ahmedusa** [comment]
i solve it. thanks.
