### ISSUE TITLE
Cannot read property 'duration'

### ISSUE THREAD

**Issue by SergiyBeno** [stjohnjohnson/cucumber-junit#21]
Hello guys.
Recently I was trying to convert cucumber .json report into .xml file using following wrapper. After the successful installation I am facing one issue which I cannot overcome or google something similar on I-net. When I run following command:

$ node_modules/.bin/cucumber-js --format=json | node_modules/.bin/cucumber-junit > output_JUnit.xml

I'm getting following error output:

if (stepJson.result.duration) {
                       ^

TypeError: Cannot read property 'duration' of undefined
    at convertStep (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:37:24)
    at /Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:104:28
    at Array.forEach (native)
    at convertScenario (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:101:10)
    at /Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:132:28
    at Array.map (native)
    at convertFeature (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:131:10)
    at /Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:153:36
    at Array.forEach (native)
    at cucumberJunit (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:152:22)

Please tell me what kind of additional information I should post under this post (environment) for you guys that can help to find an answer.

**Comment by stjohnjohnson** [comment]
Sorry you ran into trouble. Can you paste your json and cucumber version
number?
On Wed, Jan 27, 2016 at 05:15 Sergiy <notifications@github.com> wrote:

> Hello guys.
> Recently I was trying to convert cucumber .json report into .xml file
> using following wrapper. After the successful installation I am facing one
> issue which I cannot overcome or google something similar on I-net. When I
> run following command:
>
> $ node_modules/.bin/cucumber-js --format=json |
> node_modules/.bin/cucumber-junit > output_JUnit.xml
>
> I'm getting following error output:
>
> if (stepJson.result.duration) {
> ^
>
> TypeError: Cannot read property 'duration' of undefined
> at convertStep
> (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:37:24)
> at /Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:104:28
> at Array.forEach (native)
> at convertScenario
> (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:101:10)
> at /Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:132:28
> at Array.map (native)
> at convertFeature
> (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:131:10)
> at /Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:153:36
> at Array.forEach (native)
> at cucumberJunit
> (/Users/Sergiy/node_modules/cucumber-junit/lib/cucumber_junit.js:152:22)
>
> Please tell me what kind of additional information I should post under
> this post (environment) for you guys that can help to find an answer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stjohnjohnson/cucumber-junit/issues/21>.
>
-- 
-St. John

**Comment by SergiyBeno** [comment]
That's ok, thank you for quick reply. Yes, no problem - any information that can help to find workaround:
cucumber (1.3.20)
json (1.8.3)

**Comment by stjohnjohnson** [comment]
Sorry, I meant the json output of the cucumber command. My bad.
On Wed, Jan 27, 2016 at 09:28 Sergiy <notifications@github.com> wrote:

> That's ok, thank you for quick reply. Yes, no problem - any information
> that can help to find workaround:
> cucumber (1.3.20)
> json (1.8.3)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stjohnjohnson/cucumber-junit/issues/21#issuecomment-175757255>
> .
>
-- 
-St. John

**Comment by SergiyBeno** [comment]
I will attach the output below. Thank you again for your participation.
[REPORT.txt](https://github.com/stjohnjohnson/cucumber-junit/files/107317/REPORT.txt)

**Comment by SergiyBeno** [comment]
@stjohnjohnson By the way I also was wondering (maybe you know the answer because I'm not so proficient with CI) - current wrapper "converts CucumberJS JSON output into JUnitXML for software like Jenkins to read.". Does it means that Jenkins has some strict limitation regarding to input files ? What I am trying to say is:  what if I convert my .json report file into .xml file using another tool - it won't be parsed by Jenkins due to some obstacles ?

**Comment by SergiyBeno** [comment]
@stjohnjohnson how are you doing ? Hopes everything goes smoothly =)
I just wanted to ask whether have you already checked described above issue ? I just need to know - is it something that I need to do by my own and do not wait for some bug fix or there is really something that need to be fixed and pushed for public use ?

**Comment by stjohnjohnson** [comment]
What's interesting is this chunk of your JSON doesn't have a result:
```
{
    "keyword": "Given ",
    "name": "the app is running",
    "line": 35,
    "match": {
        "arguments": [
            {
                "offset": 0,
                "val": "the"
            }
        ],
        "location": "calabash-cucumber-0.16.4/features/step_definitions/calabash_steps.rb:4"
    }
}
```

**Comment by stjohnjohnson** [comment]
Okay, I have a PR open to fix it.  If everything goes well, I'll merge it and get you a new release in a few minutes.

**Comment by stjohnjohnson** [comment]
+ cucumber-junit@1.4.1

**Comment by SergiyBeno** [comment]
@stjohnjohnson hi again ! Thank you for your PR - I can confirm that issue has been successfully fixed. Thank you for your time and attention to this issue, really appreciate this =) 
I still have the last question - new output treats each `testcase` (in my case it is a scenario) as `testsuite` and each step (inside of separate scenario) as `testcase`. This is how it was originally planned ?

**Comment by stjohnjohnson** [comment]
This is expected, JUnit doesn't have another level of granularity for that information.
