### ISSUE TITLE
Fails if any output other than json

### ISSUE THREAD

**Issue by dsgill** [stjohnjohnson/cucumber-junit#29]
I have attempted to use cucumber-junit to convert the output of cucumberjs from json to junit, but I'm having a problem. The use that you indicate, piping the output of cucumberjs to cucumber-junit, fails because some packages I use and some of my code print debug statements to the console along with the json. I removed my console prints but the underlying packages still print. Writes to stderr don't appear to cause a problem but if it gets printed to stdout then your json parser stops with an error.

So I have 2 questions, either of which would enable me to use your package successfully.
1. Is it possible to tell cucumber-junit to ignore everything except the json?
2. Is it possible to have cucumber-junit take its input from a file instead of piping from a stream? When cucumberjs writes the json to a filethe other stdout/stderr prints are stripped out, so this solution would work for me.

**Comment by stjohnjohnson** [comment]
1. No, because it doesn't know it's not JSON.
2. If you can tell cucumber.js to write the json to a file, it would work.

Alternatively, you can output your debug/console statements to STDERR (`console.error`) which would not be piped into the cucumber-junit script.
