### ISSUE TITLE
Cucumber 2

### ISSUE THREAD

**Issue by JonWallsten** [stjohnjohnson/cucumber-junit#30]
I can't get this to work in Cucumber 2. Would you mind trying, to conclude if I i've made any mistakes?

**Comment by stjohnjohnson** [comment]
Cucumber has made some significant changes since 0.x, so I'm not quite sure what the new JSON format is.  If you can provide a JSON example, I might be able to help translate it and help make a PR to support 2.x.

**Comment by JonWallsten** [comment]
I could not get it to work through cucumbers cli no matter what I tried.
But I got it to work eventually using cat/type.
```
exec("\"node_modules/.bin/minicat\" ./path/cucumber.json | \"node_modules/.bin/cucumber-junit\" > ./path/cucumber_report.xml", function(err, out, code) {
    ...
});
```

**Comment by stjohnjohnson** [comment]
Awesome!  Looks to be working in v3 and v4 as well.
