### ISSUE TITLE
Cucumber 3 duration bug

### ISSUE THREAD

**Issue by LennDG** [stjohnjohnson/cucumber-junit#35]
In Cucumber version 3.x the duration of tests in the JSON output is expressed in milliseconds. 

In the translation to XML a conversion is made from nanoseconds however.
https://github.com/stjohnjohnson/cucumber-junit/blob/28197270db647916e30573e9a1f02668bcb05212/lib/cucumber_junit.js#L62

**Comment by stjohnjohnson** [comment]
Well that's interesting.  Any thoughts on how to detect which version of cucumber and correct this?

**Comment by LennDG** [comment]
Correcting would just entail multiplying the duration by 1 000 000. I don't know if cucumber 3.x reports have a distinguishing feature that would make it simple to detect though.

**Comment by stjohnjohnson** [comment]
Well since cucumber 3 is the default, I might just bump the major and fix this.

**Comment by IvanNaumenko** [comment]
Hey, In TeamCity no any changes in duration of tests

    "cucumber": "^3.2.1",
    "cucumber-html-reporter": "^3.0.4",
    "cucumber-junit": "^1.7.1",

![duration time](https://user-images.githubusercontent.com/32741530/35380040-c712ba7e-01c0-11e8-86d5-b248c2182be2.jpg)

**Comment by stjohnjohnson** [comment]
Great news!  CucumberJS v4 shipped out and reverted their migration to microseconds: https://github.com/cucumber/cucumber-js/pull/968

This bug is resolved!

**Comment by IvanNaumenko** [comment]
Hello!

Now shows incorrect duration
![incorrect_duration](https://user-images.githubusercontent.com/32741530/35734329-6d9c928e-0829-11e8-9661-fb76e2124036.png)
