### ISSUE TITLE
Parse Error On Cucumber JS output

### ISSUE THREAD

**Issue by dynamite-ready** [stjohnjohnson/cucumber-junit#7]
I'm currently running this:

node_modules/cucumber/bin/cucumber.js ./test --format=json | node_modules/cucumber-junit/bin/cucumber-junit

The yield of - node_modules/cucumber/bin/cucumber.js ./test --format=json  - is this:
```json
[
  {
    "id": "Pageload-and-Log-in",
    "name": "Pageload and Log in",
    "description": "As a "app" user\nI should find a fully loaded home page\nand should be able select a bet when not logged in",
    "line": 1,
    "keyword": "Feature",
    "uri": "path/to/feature",
    "elements": [
      {
        "name": "Confirm the page title",
        "id": "Pageload-and-Log-in;confirm-the-page-title",
        "line": 6,
        "keyword": "Scenario",
        "description": "",
        "type": "scenario",
        "steps": [
          {
            "name": "I go on the website \"http://www.url.com\"",
            "line": 7,
            "keyword": "Given ",
            "result": {
              "duration": 1509723585,
              "status": "passed"
            },
            "match": {}
          },
          {
            "name": "I check the title of the website",
            "line": 8,
            "keyword": "When ",
            "result": {
              "duration": 6951044,
              "status": "passed"
            },
            "match": {}
          },
          {
            "name": "the page title should be \"My Title\"",
            "line": 9,
            "keyword": "Then ",
            "result": {
              "duration": 40760,
              "status": "passed"
            },
            "match": {}
          }
        ]
      }
    ]
  }
]
```
But Cucumber-Junit - node_modules/cucumber-junit/bin/cucumber-junit - returns this:

SyntaxError: Unexpected token 
   at Object.parse (native)
    at cucumberJunit (/Users/leonard/Documents/projects/BDD-test-build/node_modules/cucumber-junit/lib/cucumber_junit.js:115:29)
    at Socket.<anonymous> (/Users/leonard/Documents/projects/BDD-test-build/node_modules/cucumber-junit/bin/cucumber-junit:15:26)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)

Any ideas why?

**Comment by stjohnjohnson** [comment]
I'm not sure what I can do to help at this time.  But if you run into more problems, let me know.
